### ISSUE TITLE
Twrp avail but Wsp sprout zip can't find to install twrp permanent on a/b device 

### ISSUE THREAD

**Issue by Skulking12** [SmallPP420/twrp_device_nokia_WSP_sprout#2]
Twrp avail but Wsp sprout zip can't find to install twrp permanent on a/b device

**Comment by SmallPP420** [comment]
what?

**Comment by SmallPP420** [comment]
i think i can understand you but i dont use twrp zip u directly flash from fastboot

**Comment by SmallPP420** [comment]
closed since lack of response
